"""Added a new table named title

Revision ID: 738775e68773
Revises: 9d354612f788
Create Date: 2024-04-24 16:04:15.404362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738775e68773'
down_revision = '9d354612f788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('awarded_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_awarded_date'), ['awarded_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_awarded_date'))

    op.drop_table('title')
    # ### end Alembic commands ###
