"""Add points history table

Revision ID: fcb22e91824b
Revises: c169f7f6a339
Create Date: 2024-05-03 21:19:35.686337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb22e91824b'
down_revision = 'c169f7f6a339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('points_added', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_timestamp'))

    op.drop_table('points')
    # ### end Alembic commands ###
