"""Made username non-unique

Revision ID: 4019dbaff771
Revises: 6bdff68e2f07
Create Date: 2024-04-20 21:22:05.154192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4019dbaff771'
down_revision = '6bdff68e2f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    # ### end Alembic commands ###
