"""empty message

Revision ID: 778d2afcc8af
Revises: b624e2805127
Create Date: 2024-04-07 20:06:08.902078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d2afcc8af'
down_revision = 'b624e2805127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interested_topics', sa.String(length=200), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('interested_topics')

    # ### end Alembic commands ###
