"""Added suburb field to User model

Revision ID: 6bdff68e2f07
Revises: 73aeb5b5a731
Create Date: 2024-04-20 20:24:29.276354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdff68e2f07'
down_revision = '73aeb5b5a731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suburb', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suburb')

    # ### end Alembic commands ###
