"""Added a new colum registered_date for User table

Revision ID: 15ace0653674
Revises: 738775e68773
Create Date: 2024-04-24 21:05:19.821565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ace0653674'
down_revision = '738775e68773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_registered_date'), ['registered_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_registered_date'))
        batch_op.drop_column('registered_date')

    # ### end Alembic commands ###
