"""Add vote table

Revision ID: 786ed6309014
Revises: 401216ff15fa
Create Date: 2024-03-29 22:37:35.880680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786ed6309014'
down_revision = '401216ff15fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('upvote', 'downvote'), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
