"""Add interests to user

Revision ID: b624e2805127
Revises: 7ea58cda8e84
Create Date: 2024-04-07 16:31:49.139068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b624e2805127'
down_revision = '7ea58cda8e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=200), nullable=True))
        batch_op.drop_column('topics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
